# APIs
GEMINI_API_KEY = "AIzaSyBzOPeaPGxg7sexV5zAmZg46f_1kOwmg1g"

# Configuration for aLLoyM

element_dict = {
    "AG": "Silver",
    "AL": "Aluminium",
    "AS": "Arsenic", 
    "AU": "Gold",
    "B": "Boron",
    "BA": "Barium",
    "BE": "Beryllium",
    "BI": "Bismuth",
    "C": "Carbon",
    "CA": "Calcium",
    "CD": "Cadmium",
    "CE": "Cerium",
    "CO": "Cobalt",
    "CR": "Chromium",
    "CS": "Cesium",
    "CU": "Copper",
    "DY": "Dysprosium",
    "E": "Einsteinium",
    "ER": "Erbium",
    "EU": "Europium",
    "FE": "Iron",
    "GA": "Gallium",
    "GD": "Gadolinium",
    "GE": "Germanium",
    "H": "Hydrogen",
    "HF": "Hafnium",
    "HO": "Holmium",
    "I": "Iodine",
    "IN": "Indium",
    "IR": "Iridium",
    "LA": "Lanthanum",
    "LU": "Lutetium",
    "LI": "Lithium",
    "M": "Molybdenum",
    "MG": "Magnesium",
    "MN": "Manganese",
    "MO": "Molybdenum",
    "NB": "Niobium",
    "ND": "Neodymium",
    "NI": "Nickel",
    "N": "Nitrogen",
    "NA": "Sodium",
    "O": "Oxygen",
    "OS": "Osmium",
    "P": "Phosphorus",
    "PB": "Lead",
    "PD": "Palladium",
    "PR": "Praseodymium",
    "PT": "Platinum",
    "RH": "Rhodium",
    "RE": "Rhenium",
    "SB": "Antimony",
    "SC": "Scandium",
    "SE": "Selenium",
    "SI": "Silicon",
    "SM": "Samarium",
    "SN": "Tin",
    "SR": "Strontium",
    "TA": "Tantalum",
    "TB": "Terbium",
    "TE": "Tellurium",
    "TH": "Thorium",
    "TM": "Thulium",
    "TI": "Titanium",
    "TL": "Thallium",
    "V": "Vanadium",
    "W": "Tungsten",
    "Y": "Yttrium",
    "YB": "Ytterbium",
    "ZN": "Zinc",
    "ZR": "Zirconium",
    "LA": "Lanthanum",
}

# Mapping of raw phase names to standardized names
phase_name_map = {
    "LIQ": "LIQUID",
    "RHOM": "RHOMBOHEDRAL",
    "RHOMB": "RHOMBOHEDRAL",
    "RHOMBO": "RHOMBOHEDRAL",
    "RHOM_A7": "RHOMBOHEDRAL_A7",
    "RHOMBO_A7": "RHOMBOHEDRAL_A7",
    "RHOMB_A7": "RHOMBOHEDRAL_A7",
    "BETA_1": "BETA1",
    "HEXA_A8": "HEXAGONAL_A8",
    "I_LIQUID": "IONIC_LIQUID",
    "MU_PHASE": "MU",
    "ORTHO": "ORTHORHOMBIC",
    "GAM1": "GAMMA1",
    "GAMMA_1": "GAMMA1",
    "GAM2": "GAMMA2",
    "GAMMA_2": "GAMMA2",
}

phase_list = ['RED', 'DO24', 'DIAMOND', 'B2', 'RHOMBOHEDRAL', 'HCP_A3', 'THETA', 'PSI', 'EPS', 'HEXA_A8', 'ORTHORHOMBIC', 'B2_SL', 'BETA3', 'HEXAGONAL_A8', 'FCC4', 'L11', 'GAMMA_P', 'SIGMA1', 'C11', 'CBCC_A12', 'GAMMA_1', 'HCP', 'RHOMB', 'C36', 'RHO', 'RHOMBOHEDRAL_A7', 'BCC_B2', 'K_CARBIDE', 'C14', 'BETA', 'FCC_A1', 'HALITE', 'ORDER', 'FCC', 'LAVES_C15', 'PHI', 'I_LIQUID', 'CUB_A13', 'ETA1', 'BCT', 'MU_PHASE', 'LAVES_C14', 'ORTHO', 'L12', 'TETRAGONAL_A6', 'IONIC_LIQUID', 'LAV_C15', 'DIAMOND_A4', 'LAV_C14', 'BETA1', 'C15', 'GAMMA', 'GAMMA2', 'LAVES_C36', 'EPSILON', 'DIS_FCC', 'RHOMB_C19', 'TET', 'BCC4', 'GAM1', 'H_SIGMA', 'BETA2', 'RHOM', 'DELTA', 'EPS2', 'SIGMA', 'BETA_1', 'A12', 'GAM2', 'CBCC', 'CHI', 'ETA2', 'BCC2', 'ZETA', 'BCT_A5', 'CUB', 'B2_BCC', 'ALPHA', 'R_PHASE', 'ALPHA_1', 'BCC_A2', 'SPINEL', 'ETA', 'MU', 'LIQUID', 'BCC', 'GRAPHITE', 'RHOMBO', 'DHCP', 'GAMMA1', 'CEC2L', 'CEC2H']